// eslint-disable-next-line
export default [
  {
    id: 1,
    title: "Essential cotton-blend",
    img: 1,
    price: 200,
    discountedPrice: 100,
    rating: 4,
    reviews: 4,
    colors: ["red", "yellow", "green"],
    size: ["S", "XL"],
    category: "lifestyle",
  },
  {
    id: 2,
    title: "Flecked cotton-blend",
    img: 2,
    price: 175,
    discountedPrice: false,
    rating: 3,
    reviews: 10,
    colors: ["red", "yellow"],
    size: ["S", "XL", "M"],
    category: "running",
  },
  {
    id: 3,
    title: "Striped cotton t-shirt",
    img: 3,
    price: 200,
    discountedPrice: false,
    rating: 5,
    reviews: 15,
    colors: ["red", "green", "black"],
    size: ["S", "M"],
    category: "training",
  },
  {
    id: 4,
    title: "V-neck cotton t-shirt",
    img: 4,
    price: 100,
    discountedPrice: false,
    rating: 4.5,
    reviews: 12,
    colors: ["black"],
    size: ["S", "M"],
    category: "clothing",
  },
  {
    id: 5,
    title: "Message cotton t-shirt",
    img: 5,
    price: 100,
    discountedPrice: false,
    rating: 5,
    reviews: 23,
    colors: ["red", "green"],
    size: ["S", "L"],
    category: "scarves",
  },
  {
    id: 6,
    title: "Sequin star t-shirt",
    img: 6,
    price: 200,
    discountedPrice: 100,
    rating: 4.5,
    reviews: 21,
    colors: ["yellow", "green"],
    size: ["S", "L"],
    category: "scarves",
  },
  {
    id: 7,
    title: "Ruffle sleeve t-shirt",
    img: 7,
    price: 175,
    discountedPrice: false,
    rating: 3.5,
    reviews: 30,
    colors: ["yellow"],
    size: ["S", "L", "XL"],
    category: "accesories",
  },
  {
    id: 8,
    title: "Double layer top",
    img: 8,
    price: 200,
    discountedPrice: false,
    rating: 4,
    reviews: 36,
    colors: ["green"],
    size: ["S", "L", "XL"],
    category: "shoes",
  },
  {
    id: 9,
    title: "Nike Dry Swoosh",
    img: 9,
    price: 200,
    discountedPrice: 100,
    rating: 4.5,
    reviews: 46,
    colors: ["green", "yellow"],
    size: ["S", "L", "XL"],
    category: "fragrance",
  },
  {
    id: 10,
    title: "football shirt",
    img: 10,
    price: 300,
    discountedPrice: 150,
    rating: 4,
    reviews: 52,
    colors: ["green", "yellow"],
    size: ["S", "L"],
    category: "football",
  },
  {
    id: 11,
    title: "fragrence shirt",
    img: 11,
    price: 200,
    discountedPrice: false,
    rating: 4,
    reviews: 52,
    colors: ["green", "red", "yellow"],
    size: ["S", "L"],
    category: "fragrance",
  },
  {
    id: 12,
    title: "good shoes",
    img: 12,
    price: 120,
    discountedPrice: false,
    rating: 3.5,
    reviews: 52,
    colors: ["green", "red", "yellow"],
    size: ["S"],
    category: "shoes",
  },
  {
    id: 13,
    title: "accesories1",
    img: 13,
    price: 60,
    discountedPrice: false,
    rating: 4,
    reviews: 13,
    colors: ["green", "red", "yellow"],
    size: ["S"],
    category: "accesories",
  },
  {
    id: 14,
    title: "scarves1",
    img: 14,
    price: 130,
    discountedPrice: false,
    rating: 5,
    reviews: 15,
    colors: ["green", "red", "yellow"],
    size: ["S", "M"],
    category: "scarves",
  },
  {
    id: 15,
    title: "clothing shirt",
    img: 15,
    price: 70,
    discountedPrice: false,
    rating: 5,
    reviews: 130,
    colors: ["green"],
    size: ["S", "M"],
    category: "clothing",
  },
  {
    id: 16,
    title: "clothing shirt2",
    img: 16,
    price: 70,
    discountedPrice: false,
    rating: 5,
    reviews: 130,
    colors: ["green", "red"],
    size: ["S", "M"],
    category: "clothing",
  },
  {
    id: 17,
    title: "training 1",
    img: 17,
    price: 70,
    discountedPrice: false,
    rating: 2,
    reviews: 150,
    colors: ["green", "red"],
    size: ["S", "M"],
    category: "training",
  },
  {
    id: 18,
    title: "training 2",
    img: 18,
    price: 105,
    discountedPrice: 80,
    rating: 2,
    reviews: 68,
    colors: ["green", "red", "yellow"],
    size: ["S", "M"],
    category: "training",
  },
  {
    id: 19,
    title: "lifestyle 1",
    img: 19,
    price: 135,
    discountedPrice: false,
    rating: 3,
    reviews: 75,
    colors: ["green", "red", "yellow"],
    size: ["S", "M"],
    category: "lifestyle",
  },
  {
    id: 20,
    title: "lifestyle 2",
    img: 20,
    price: 135,
    discountedPrice: false,
    rating: 3,
    reviews: 75,
    colors: ["green", "red", "yellow"],
    size: ["S", "M", "XL"],
    category: "lifestyle",
  },
  {
    id: 21,
    title: "running 1",
    img: 21,
    price: 60,
    discountedPrice: false,
    rating: 4.5,
    reviews: 123,
    colors: ["green", "red", "yellow"],
    size: ["M", "XL"],
    category: "running",
  },
  {
    id: 22,
    title: "running 2",
    img: 22,
    price: 80,
    discountedPrice: false,
    rating: 5,
    reviews: 234,
    colors: ["green", "red", "yellow"],
    size: ["S", "M", "XL"],
    category: "running",
  },
  {
    id: 23,
    title: "accesories 2",
    img: 23,
    price: 95,
    discountedPrice: 80,
    rating: 5,
    reviews: 120,
    colors: ["green", "red", "yellow"],
    size: ["S", "M", "XL"],
    category: "accesories",
  },
  {
    id: 24,
    title: "clothing 2",
    img: 24,
    price: 95,
    discountedPrice: 80,
    rating: 1,
    reviews: 120,
    colors: ["green", "red", "yellow"],
    size: ["S", "M", "XL"],
    category: "clothing",
  },
  {
    id: 25,
    title: "clothing 3",
    img: 25,
    price: 130,
    discountedPrice: false,
    rating: 2.5,
    reviews: 26,
    colors: ["green", "red", "yellow"],
    size: ["S", "M", "XL"],
    category: "clothing",
  },
]
